import { css } from '@emotion/react';
import Head from 'next/head';

export default function Home() {
  const test = css`
    color: red;
    font-size: 24px;
  `;

  return (
    <>
      <Head>
        <title>Shopping Site</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <div css={test}>Hello world</div>
    </>
  );
}
