import Head from 'next/head';

import { Header } from 'components/ui/parts/header/Header';
import { HomeSection } from 'components/ui/layouts/index/home/HomeSection';
import { AboutSection } from 'components/ui/layouts/index/about/AboutSection';
import { MenuSection } from 'components/ui/layouts/index/menu/MenuSection';
import { ServiceSection } from 'components/ui/layouts/index/service/ServiceSection';
import { Footer } from 'components/ui/parts/footer/Footer';

export const IndexContents = () => {
  return (
    <>
      <Head>
        <title>Shopping Site</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <Header />
      <HomeSection />
      <AboutSection />
      <MenuSection />
      <ServiceSection />
      <Footer />
    </>
  );
};
